### ISSUE TITLE
Play sound not working..

### ISSUE THREAD

**Issue by Eaves628** [navaneethkm004/Discord-24x7-Radio-Bot#4]
So i dont know if im the only one, but the bot works perfectly except one issue. When you !play (url), it joins the voice channel but it doesn't play the song. The !nowplaying also says the sound is playing and !volume says the volume is at max. But i can;t hear the song. Please fix this..

**Comment by navaneethkm004** [comment]
It's simple. Just run `npm i ffmpeg ffmpeg-static` on repl terminal
